apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: post.created
  namespace: kafka
  labels:
    strimzi.io/cluster: reghub-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: post.deleted
  namespace: kafka
  labels:
    strimzi.io/cluster: reghub-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
