apiVersion: v1
kind: Secret
metadata:
  name: reghub-secret
  namespace: reghub
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: reghub_password
  AWS_ACCESS_KEY_ID: replace-me
  AWS_SECRET_ACCESS_KEY: replace-me

