apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: reghub
type: Opaque
stringData:
  MYSQL_DATABASE: reghub
  MYSQL_USER: reghub
  MYSQL_PASSWORD: reghub_password
  MYSQL_ROOT_PASSWORD: root_password

