apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: reghub
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: reghub-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
  SPRING_KAFKA_CONSUMER_GROUP_ID: notification-service
  APP_KAFKA_TOPIC_POST_CREATED: post.created
